import React from 'react'
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center text-white">
        <div className="container flex flex-col items-center justify-center gap-4 px-4">
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-[5rem]">
            Chore <span className='text-emerald-500'>App</span>
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
